### ISSUE TITLE
Wrong method call in CustomPlayersHandler::loadExit(...)

### ISSUE THREAD

**Issue by Darkluke1111** [jubiman/CustomPlayerLib#2]
CustomPlayersHandler calls loadEnter on its CustomPlayer objects in its loadExit method (Line 115) but should call loadExit:

https://github.com/jubiman/CustomPlayerLib/blob/9d6e016c848687955e929b03eb628fc0170fd40d/src/main/java/com/jubiman/customplayerlib/CustomPlayersHandler.java#L113C1-L116C3

**Comment by jubiman** [comment]
Cannot believe how this bug made it into the current version and hasn't been fixed by me in 7 months xD. I'm currently fixing it and redeploying the artifact. It should be fixed within an hour from now

**Comment by jubiman** [comment]
While setting up the dev environment on my laptop, I realized that I don't have the key used to sign the artifact, so I can't push it to maven.
What I'll do is:

1. Update the source code to fix the bug
2. Upload the updated mod to Steam, so the consumer will have the updated product
3. Upload the jar to GitHub releases on this repository, so you can manually add it to your dev environment
4. Try to publish it to GitHub packages (as it might not require me to sign the artifact), so you might be able to skip 3.
5. Whenever I get access to my desktop again (should take around 5 weeks), publish the jar to maven

**Comment by Darkluke1111** [comment]
No rush. I don't really care whether my stuff gets loaded before or after the base player data for my use case. I just stumbled upon this issue while looking through the code so I reported it.

**Comment by jubiman** [comment]
Many thanks about that xD

It seems like I was able to push it to GitHub packages alright so I'm closing this issue.
You might have to add the following bit of code to your `build.gradle` file in the `repositories` object:
```java
maven {
     url "https://maven.pkg.github.com/jubiman/CustomPlayerLib"
}
``` 

Just in case this does not work, I have uploaded a development release jar you can use to manually add the dependency at compile-time (as the steam mod is used at runtime).
https://github.com/jubiman/CustomPlayerLib/releases/latest
